### PR TITLE
Add a variable to control suffix text in the modeline

### PR DESCRIPTION
**Pull request by aksharvarma**
This should address Issue #7

### CODE REVIEW

**Comment by lassik** [comment]
I like this feature, but we should combine it with the implementation of #1 (since one might want a different suffix text for `NN.NN years` and `AA.AA/BB years`. @alraban thoughts?

**Comment by lassik** [comment]
Also another possible format `XX.XX years left`.

**Comment by aksharvarma** [comment]
For me #1 would be difficult to implement while this was something I could attempt myself. It is also something I want more than the acturial death date feature.

Regarding getting the acturial table data into this package,
* Is it going to be kept in this repo? I am not good enough with elisp data structures to attempt something like that.
* Or will the package have to go online every time it updates the age calculation? I would not be too happy with a package that accesses the internet every day to maintain full functionality.

**Comment by aksharvarma** [comment]
I should clarify that I am not against the acturial date feature, if someone implements it I would mostly use it myself.

I'm just of the opinion that there is no need to put this feature on hold until that feature implemented.

**Comment by lassik** [comment]
> For me #1 would be difficult to implement while this was something I could attempt myself. It is also something I want more than the acturial death date feature.

I respect that and agree. We can write the code as a group effort.

> Regarding getting the acturial table data into this package,
> 
> * Is it going to be kept in this repo? I am not good enough with elisp data structures to attempt something like that.

I would be in favor of not including any tables / formulas in this package because:

1. It's not clear which tables to use (they vary per country and based on many factors).
2. I personally think relying on average outcomes is not wise. To have the best chance against future regrets, it's wiser to assume a bad outcome.
3. Life is not about its length but the sum of your experiences; for most people it's better to have a bit of urgency and get to those experiences sooner. To people who have _too many_ experiences, their body eventually sends a strong signal to rest; to people who have too few, the body doesn't send enough signals and life hacks such as this package are the main reminder.

> * Or will the package have to go online every time it updates the age calculation? I would not be too happy with a package that accesses the internet every day to maintain full functionality.

I agree. I wouldn't put in any internet access.

> I should clarify that I am not against the acturial date feature, if someone implements it I would mostly use it myself.

Would it work that people who want to use the tables can look them up on the internet? If there are some standard tables, we can link to them from the readme so people can find them easily.

> I'm just of the opinion that there is no need to put this feature on hold until that feature implemented.

I agree that actuarial tables would be complex to implement. But if we just give users the ability to enter an arbitrary end date or age, that's quite simple and we can get it done soon.

**Comment by aksharvarma** [comment]
> I agree that actuarial tables would be complex to implement. But if we just give users the ability to enter an arbitrary end date or age, that's quite simple and we can get it done soon.

I agree with everything you said and this sounds reasonable. I can try and implement something like that. Should I do it in a new pull request?

**Comment by lassik** [comment]
Thanks for volunteering! Doesn't matter which pull request is used - whichever way you prefer to do it :) Before we start, it would be nice to get a third opinion from @alraban on how to do things since he requested #1.

**Comment by alraban** [comment]
With respect to this pull request, I think creating a variable to allow the user to choose their own string as a suffix is a good solution, as that offers the most flexibility in describing what is displayed, regardless of what is ultimately displayed, if that makes sense.

**Comment by lassik** [comment]
@alraban Do you have time / elisp skills to work on this? I'm very busy with the Scheme programming language and other stuff right now so elisp time is quite limited.

**Comment by alraban** [comment]
I have very limited elisp skills unfortunately, but I can certainly try to take a hack at it.  That said, this pull request looks like a good solution to the suffix issue already; did you mean to suggest I take a hack at a pull for #1 ?

**Comment by mateialexandru** [comment]
@lassik let's get this in now! I see #1 as orthogonal to this. Thoughts?

**Comment by doolio** [comment]
Yes, I don't think there is a reason not to merge this.

**Comment by gvol** [comment]
Thank you @aksharvarma for this contribution!  I have updated how it works, however, and I think this is now obsolete.  You can customize `memento-mori-mementos` with any message(s) that you want, so basically a prefix and/or suffix.

I'm going to go ahead and close this, but please feel free to open a new PR (or issue) if there is something else you would like to see changed!  I really do appreciate your work on this.

**Pull request closed without merging**
